server.port=8080
spring.application.name=Java21SbEncryptionHashingNSalting
spring.data.mongodb.uri=mongodb://localhost:27017/users
spring.data.mongodb.database=encryption_hashing_salting
secretKey=1234567890098765
encDecAlgo=AES